// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: production_line.proto

package models

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Possible industry values
type Industry int32

const (
	Industry_INDUSTRY_UNSPECIFIED  Industry = 0
	Industry_INDUSTRY_FLOAT        Industry = 1
	Industry_INDUSTRY_PATTERNED    Industry = 2
	Industry_INDUSTRY_CONTAINER    Industry = 3
	Industry_INDUSTRY_COMPOSITE    Industry = 4
	Industry_INDUSTRY_INSULATION   Industry = 5
	Industry_INDUSTRY_BOROSILICATE Industry = 6
)

// Enum value maps for Industry.
var (
	Industry_name = map[int32]string{
		0: "INDUSTRY_UNSPECIFIED",
		1: "INDUSTRY_FLOAT",
		2: "INDUSTRY_PATTERNED",
		3: "INDUSTRY_CONTAINER",
		4: "INDUSTRY_COMPOSITE",
		5: "INDUSTRY_INSULATION",
		6: "INDUSTRY_BOROSILICATE",
	}
	Industry_value = map[string]int32{
		"INDUSTRY_UNSPECIFIED":  0,
		"INDUSTRY_FLOAT":        1,
		"INDUSTRY_PATTERNED":    2,
		"INDUSTRY_CONTAINER":    3,
		"INDUSTRY_COMPOSITE":    4,
		"INDUSTRY_INSULATION":   5,
		"INDUSTRY_BOROSILICATE": 6,
	}
)

func (x Industry) Enum() *Industry {
	p := new(Industry)
	*p = x
	return p
}

func (x Industry) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Industry) Descriptor() protoreflect.EnumDescriptor {
	return file_production_line_proto_enumTypes[0].Descriptor()
}

func (Industry) Type() protoreflect.EnumType {
	return &file_production_line_proto_enumTypes[0]
}

func (x Industry) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Industry.Descriptor instead.
func (Industry) EnumDescriptor() ([]byte, []int) {
	return file_production_line_proto_rawDescGZIP(), []int{0}
}

// Possible segment values
type Segment int32

const (
	Segment_SEGMENT_UNSPECIFIED  Segment = 0
	Segment_SEGMENT_ENDPORT      Segment = 1
	Segment_SEGMENT_CROSSFIRED   Segment = 2
	Segment_SEGMENT_OXYGEN       Segment = 3
	Segment_SEGMENT_HYBRID       Segment = 4
	Segment_SEGMENT_ALL_ELECTRIC Segment = 5
	Segment_SEGMENT_RECUPERATIVE Segment = 6
)

// Enum value maps for Segment.
var (
	Segment_name = map[int32]string{
		0: "SEGMENT_UNSPECIFIED",
		1: "SEGMENT_ENDPORT",
		2: "SEGMENT_CROSSFIRED",
		3: "SEGMENT_OXYGEN",
		4: "SEGMENT_HYBRID",
		5: "SEGMENT_ALL_ELECTRIC",
		6: "SEGMENT_RECUPERATIVE",
	}
	Segment_value = map[string]int32{
		"SEGMENT_UNSPECIFIED":  0,
		"SEGMENT_ENDPORT":      1,
		"SEGMENT_CROSSFIRED":   2,
		"SEGMENT_OXYGEN":       3,
		"SEGMENT_HYBRID":       4,
		"SEGMENT_ALL_ELECTRIC": 5,
		"SEGMENT_RECUPERATIVE": 6,
	}
)

func (x Segment) Enum() *Segment {
	p := new(Segment)
	*p = x
	return p
}

func (x Segment) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Segment) Descriptor() protoreflect.EnumDescriptor {
	return file_production_line_proto_enumTypes[1].Descriptor()
}

func (Segment) Type() protoreflect.EnumType {
	return &file_production_line_proto_enumTypes[1]
}

func (x Segment) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Segment.Descriptor instead.
func (Segment) EnumDescriptor() ([]byte, []int) {
	return file_production_line_proto_rawDescGZIP(), []int{1}
}

// Basic information of a production line
type ProductionLineBasicInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductionLineBasicInfo) Reset() {
	*x = ProductionLineBasicInfo{}
	mi := &file_production_line_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductionLineBasicInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductionLineBasicInfo) ProtoMessage() {}

func (x *ProductionLineBasicInfo) ProtoReflect() protoreflect.Message {
	mi := &file_production_line_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductionLineBasicInfo.ProtoReflect.Descriptor instead.
func (*ProductionLineBasicInfo) Descriptor() ([]byte, []int) {
	return file_production_line_proto_rawDescGZIP(), []int{0}
}

func (x *ProductionLineBasicInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProductionLineBasicInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Production line with complete information
type ProductionLine struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Industry      Industry               `protobuf:"varint,3,opt,name=industry,proto3,enum=models.Industry" json:"industry,omitempty"`
	Segment       Segment                `protobuf:"varint,4,opt,name=segment,proto3,enum=models.Segment" json:"segment,omitempty"`
	PlantID       string                 `protobuf:"bytes,5,opt,name=plantID,proto3" json:"plantID,omitempty"`
	TenantID      string                 `protobuf:"bytes,6,opt,name=tenantID,proto3" json:"tenantID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductionLine) Reset() {
	*x = ProductionLine{}
	mi := &file_production_line_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductionLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductionLine) ProtoMessage() {}

func (x *ProductionLine) ProtoReflect() protoreflect.Message {
	mi := &file_production_line_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductionLine.ProtoReflect.Descriptor instead.
func (*ProductionLine) Descriptor() ([]byte, []int) {
	return file_production_line_proto_rawDescGZIP(), []int{1}
}

func (x *ProductionLine) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProductionLine) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductionLine) GetIndustry() Industry {
	if x != nil {
		return x.Industry
	}
	return Industry_INDUSTRY_UNSPECIFIED
}

func (x *ProductionLine) GetSegment() Segment {
	if x != nil {
		return x.Segment
	}
	return Segment_SEGMENT_UNSPECIFIED
}

func (x *ProductionLine) GetPlantID() string {
	if x != nil {
		return x.PlantID
	}
	return ""
}

func (x *ProductionLine) GetTenantID() string {
	if x != nil {
		return x.TenantID
	}
	return ""
}

// Request for creating or updating a production line
type ProductionLineCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Industry      Industry               `protobuf:"varint,2,opt,name=industry,proto3,enum=models.Industry" json:"industry,omitempty"`
	Segment       Segment                `protobuf:"varint,3,opt,name=segment,proto3,enum=models.Segment" json:"segment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductionLineCreateRequest) Reset() {
	*x = ProductionLineCreateRequest{}
	mi := &file_production_line_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductionLineCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductionLineCreateRequest) ProtoMessage() {}

func (x *ProductionLineCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_production_line_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductionLineCreateRequest.ProtoReflect.Descriptor instead.
func (*ProductionLineCreateRequest) Descriptor() ([]byte, []int) {
	return file_production_line_proto_rawDescGZIP(), []int{2}
}

func (x *ProductionLineCreateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductionLineCreateRequest) GetIndustry() Industry {
	if x != nil {
		return x.Industry
	}
	return Industry_INDUSTRY_UNSPECIFIED
}

func (x *ProductionLineCreateRequest) GetSegment() Segment {
	if x != nil {
		return x.Segment
	}
	return Segment_SEGMENT_UNSPECIFIED
}

var File_production_line_proto protoreflect.FileDescriptor

const file_production_line_proto_rawDesc = "" +
	"\n" +
	"\x15production_line.proto\x12\x06models\x1a\x1bbuf/validate/validate.proto\"G\n" +
	"\x17ProductionLineBasicInfo\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xe1\x01\n" +
	"\x0eProductionLine\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x126\n" +
	"\bindustry\x18\x03 \x01(\x0e2\x10.models.IndustryB\b\xbaH\x05\x82\x01\x02\x10\x01R\bindustry\x123\n" +
	"\asegment\x18\x04 \x01(\x0e2\x0f.models.SegmentB\b\xbaH\x05\x82\x01\x02\x10\x01R\asegment\x12\x18\n" +
	"\aplantID\x18\x05 \x01(\tR\aplantID\x12\x1a\n" +
	"\btenantID\x18\x06 \x01(\tR\btenantID\"\x81\x05\n" +
	"\x1bProductionLineCreateRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x126\n" +
	"\bindustry\x18\x02 \x01(\x0e2\x10.models.IndustryB\b\xbaH\x05\x82\x01\x02\x10\x01R\bindustry\x123\n" +
	"\asegment\x18\x03 \x01(\x0e2\x0f.models.SegmentB\b\xbaH\x05\x82\x01\x02\x10\x01R\asegment:\xe0\x03\xbaH\xdc\x03\x1a\xd9\x03\n" +
	"\x19industry.allowed.segments\x12/unsupported combination of industry and segment\x1a\x8a\x03(this.industry == 1) ? (this.segment >= 2 && this.segment <= 3) :(this.industry == 2) ? (this.segment >= 1 && this.segment <= 3) :(this.industry == 3) ? (this.segment >= 1 && this.segment <= 6) :(this.industry == 4) ? (this.segment >= 3 && this.segment <= 6) :(this.industry == 5) ? (this.segment == 3 || this.segment == 5) :(this.industry == 6) ? (this.segment >= 3 && this.segment <= 5) :true*\xb4\x01\n" +
	"\bIndustry\x12\x18\n" +
	"\x14INDUSTRY_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eINDUSTRY_FLOAT\x10\x01\x12\x16\n" +
	"\x12INDUSTRY_PATTERNED\x10\x02\x12\x16\n" +
	"\x12INDUSTRY_CONTAINER\x10\x03\x12\x16\n" +
	"\x12INDUSTRY_COMPOSITE\x10\x04\x12\x17\n" +
	"\x13INDUSTRY_INSULATION\x10\x05\x12\x19\n" +
	"\x15INDUSTRY_BOROSILICATE\x10\x06*\xab\x01\n" +
	"\aSegment\x12\x17\n" +
	"\x13SEGMENT_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fSEGMENT_ENDPORT\x10\x01\x12\x16\n" +
	"\x12SEGMENT_CROSSFIRED\x10\x02\x12\x12\n" +
	"\x0eSEGMENT_OXYGEN\x10\x03\x12\x12\n" +
	"\x0eSEGMENT_HYBRID\x10\x04\x12\x18\n" +
	"\x14SEGMENT_ALL_ELECTRIC\x10\x05\x12\x18\n" +
	"\x14SEGMENT_RECUPERATIVE\x10\x06Bc\n" +
	"\n" +
	"com.modelsB\x13ProductionLineProtoP\x01Z\b./models\xa2\x02\x03MXX\xaa\x02\x06Models\xca\x02\x06Models\xe2\x02\x12Models\\GPBMetadata\xea\x02\x06Modelsb\x06proto3"

var (
	file_production_line_proto_rawDescOnce sync.Once
	file_production_line_proto_rawDescData []byte
)

func file_production_line_proto_rawDescGZIP() []byte {
	file_production_line_proto_rawDescOnce.Do(func() {
		file_production_line_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_production_line_proto_rawDesc), len(file_production_line_proto_rawDesc)))
	})
	return file_production_line_proto_rawDescData
}

var file_production_line_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_production_line_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_production_line_proto_goTypes = []any{
	(Industry)(0),                       // 0: models.Industry
	(Segment)(0),                        // 1: models.Segment
	(*ProductionLineBasicInfo)(nil),     // 2: models.ProductionLineBasicInfo
	(*ProductionLine)(nil),              // 3: models.ProductionLine
	(*ProductionLineCreateRequest)(nil), // 4: models.ProductionLineCreateRequest
}
var file_production_line_proto_depIdxs = []int32{
	0, // 0: models.ProductionLine.industry:type_name -> models.Industry
	1, // 1: models.ProductionLine.segment:type_name -> models.Segment
	0, // 2: models.ProductionLineCreateRequest.industry:type_name -> models.Industry
	1, // 3: models.ProductionLineCreateRequest.segment:type_name -> models.Segment
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_production_line_proto_init() }
func file_production_line_proto_init() {
	if File_production_line_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_production_line_proto_rawDesc), len(file_production_line_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_production_line_proto_goTypes,
		DependencyIndexes: file_production_line_proto_depIdxs,
		EnumInfos:         file_production_line_proto_enumTypes,
		MessageInfos:      file_production_line_proto_msgTypes,
	}.Build()
	File_production_line_proto = out.File
	file_production_line_proto_goTypes = nil
	file_production_line_proto_depIdxs = nil
}
