name: Release IM contract

on:
  workflow_dispatch:
    inputs:
      versionType:
        description: 'What type of new version to release?'
        required: true
        type: choice
        options:
          - major
          - minor
          - patch
        default: minor

permissions:
  contents: write

env:
  ORG_NAME: Edhouse-SW-Miners
  PROTO_REPO_NAME: nucleus-contract-poc
  TARGET_REPO_NAME: nucleus-im-contract
  SOURCE_DIR: proto_src
  TARGET_DIR: target_repo

jobs:
  generate-im-go:
    runs-on: ubuntu-latest
    steps:
      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.EDBOTAPP_ID }}
          private-key: ${{ secrets.EDBOTAPP_KEY }}
          owner: ${{ env.ORG_NAME }}
          repositories: ${{ env.TARGET_REPO_NAME }}

      - name: Checkout '${{ env.PROTO_REPO_NAME }}' repository
        uses: actions/checkout@v4
        with:
          path: ${{ env.SOURCE_DIR }}

      - name: Checkout target repo '${{ env.ORG_NAME }}/${{ env.TARGET_REPO_NAME }}'
        uses: actions/checkout@v4
        with:
          token: ${{ steps.generate-token.outputs.token }}
          repository: ${{ env.ORG_NAME }}/${{ env.TARGET_REPO_NAME }}
          path: ${{ env.TARGET_DIR }}

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.4

      - name: Set up buf
        uses: bufbuild/buf-action@v1
        with:
          setup_only: true

      - name: Install protoc-gen-go
        run: go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.36.8

      - name: Generate stubs
        working-directory: ${{ env.SOURCE_DIR }}/im
        run: buf generate --template ../buf.gen.yaml

      - name: Initialize or update Go module
        working-directory: ${{ env.SOURCE_DIR }}/im/gen/go
        run: |
          if [ ! -f go.mod ]; then
            go mod init github.com/${{ env.ORG_NAME }}/${{ env.TARGET_REPO_NAME }}/go
          fi
          go mod tidy

      - name: Copy generated stubs to target repo
        run: |
          rsync -av --delete ${{ env.SOURCE_DIR }}/im/gen/go/ ${{ env.TARGET_DIR }}/go/

      - name: Format Go files
        working-directory: ${{ env.TARGET_DIR }}/go
        run: go fmt ./...

      - name: Configure git
        working-directory: ${{ env.TARGET_DIR }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit changes
        working-directory: ${{ env.TARGET_DIR }}
        run: |
          git add .
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Release IM contract version"
          fi

      - name: Push changes
        working-directory: ${{ env.TARGET_DIR }}
        run: git push origin main